<MyButton@Button>:
    halign: 'left'
    font_size: '16sp'
    markup: True

<FormLabel@Label>
    size_hint_y: None
    size: (self.parent.width, '36dp')
    text_size: self.parent.width, None
    halign: 'left'
    valign: 'middle'
    markup: False

<FormTextInput@TextInput>
    size_hint_y: None
    size: (self.parent.width, '36dp')
    multiline: False
    allow_copy: True
    use_bubble: True

<FormTextArea@FormTextInput>:
    multiline: True
    max_chars: 512
